# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  nodename: one
  advertise_ip: 172.10.1.1
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO

  data_dir: /var/lib/teleport
  storage:
      path: /var/lib/teleport/backend
      type: dir

auth_service:
  enabled: yes

  authentication:
    type: local
    second_factor: off

  cluster_name: one
  tokens: 
       - "node,auth,proxy:foo"
       - "trustedcluster:bar"

ssh_service:
  enabled: yes
  labels:
      cluster: one
  commands:
      - name: kernel
        command: [/bin/uname, -r]
        period: 5m

proxy_service:
  enabled: yes

